import type { ReportData } from './types';

export const INITIAL_REPORT_DATA: ReportData = {
    title: "英雄联盟职业选手测试记录表",
    subtitle: "姓名：",
    player_name: "马炼 (Ma Lian)",
    date_info: "数据采集日期：2025年10月 | 运动营养与恢复智能科学创新中心",
    archive_name: "马炼",
    archive_dob: "2005年8月",
    archive_age: "20岁",
    archive_game: "英雄联盟 (LOL)",
    core_desc: "评估选手即时操作和决策效率的最关键指标。",
    apm_value: "209",
    apm_eval: "评估：优秀。高于平均水平，基础操作熟练度高。",
    reaction_value: "0.131",
    reaction_eval: "评估：极佳。反应迅捷，有利于游戏内快速判断和执行。",
    mouse_score: "137",
    mouse_eval_value: "87%",
    mouse_eval_text: "目标效率 87%，准确率 78%。有 22% 提升空间，需专项训练。",
    health_title_1: "1. 基础维度与体态",
    bmi_value: "176.9 cm / 73.3 kg",
    wc_value: "82 cm",
    hc_value: "103 cm",
    body_eval: "适中 (BMI 正常)",
    whr_value: "0.795",
    whr_eval: "理想范围 (内脏脂肪风险低)",
    health_title_2: "2. 心肺功能 (Cardiopulmonary Health)",
    hr_value: "78 次/分",
    hr_advice: "正常范围偏高，建议加强有氧训练。",
    bp_value: "124 / 69 mmHg",
    fvc_value: "5212 ml (优秀)",
    health_title_3: "3. 肌肉力量与爆发力",
    grip_value: "48.6 kg",
    grip_eval: "接近优秀水平，抵抗疲劳力良好。",
    jump_value: "42.1 cm",
    jump_eval: "下肢爆发力良好，有利于保持身体活力。",
    posture_title_1: "1. 颈/腰椎活动度 (久坐风险)",
    cervical_joint: "颈椎",
    cervical_flex: "35°",
    cervical_ext: "60°",
    cervical_lat: "52° / 50°",
    cervical_eval: "良好，后伸 60° 表明活动度优秀，姿势控制尚可。",
    lumbar_joint: "腰椎",
    lumbar_flex: "90°",
    lumbar_ext: "25°",
    lumbar_lat: "22° / 20°",
    lumbar_eval: "前屈 90° 极佳（可能代偿）。<strong>后伸 25° 需关注</strong>，增加腰背核心稳定训练。",
    posture_title_2: "2. 下肢功能失衡 YBT 测试 (星状平衡)",
    ybt_desc: "数值差距越大，失衡风险越高。",
    ybt_ant_dir: "前侧",
    ybt_ant_l: "78",
    ybt_ant_r: "60",
    ybt_ant_diff: "18",
    ybt_ant_risk: "风险高。 右侧膝踝稳定性/柔韧性急需加强。",
    ybt_pl_dir: "后外侧",
    ybt_pl_l: "86",
    ybt_pl_r: "104",
    ybt_pl_diff: "18",
    ybt_pl_risk: "风险高。 左侧髋关节/踝关节稳定性需提升。",
    ybt_pm_dir: "后内侧",
    ybt_pm_l: "78",
    ybt_pm_r: "66",
    ybt_pm_diff: "12",
    ybt_pm_risk: "风险中。 右侧内收肌群/髋关节控制力偏弱。",
    summary_advantage_title: "核心优势：",
    summary_advantage_content: "极快的反应速度 (<span class=\"font-extrabold text-gray-900\">0.131</span>秒) 和高 APM (<span class=\"font-extrabold text-gray-900\">209</span>)；心肺功能优秀。",
    summary_risk_title: "健康风险：",
    summary_risk_content: "下肢功能<strong>严重失衡</strong>。YBT 测试显示左右两侧多方向差距大 (12~18 cm)，可能导致右下肢代偿，增加膝盖和踝关节损伤风险。",
    summary_focus_title: "训练重点：",
    summary_focus_content: "立即启动<strong>右侧下肢</strong>（尤其是前侧）的柔韧性、稳定性和力量强化训练。同时加强<strong>腰背核心</strong>的稳定性和后伸活动度。"
};